config/routes.rb
FacebookActivity::Application.routes.draw do
  root to: 'index#index'

  get "users/get_my_location"

  # auth routes
  match '/login', to: 'sessions#new', as: 'login', via: [:get]
  match '/auth/:provider/callback', to: 'sessions#create', as: 'auth_callback', via: [:get, :post]
  match '/auth/failure', to: 'sessions#failure', as: 'auth_failure', via: [:get, :post]
  match '/auth/destroy', to: 'sessions#destroy', as: 'sign_out', via: :delete
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="http://railstutorial.org/">Rails Tutorial</a>
		by Michael Hartl
	</small>
	<nav>
		<ul>
			<li><a href="http://news.railstutorial.org/">News</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "Nouscourse", root_path, id: "logo" %>
			<nav>
              <ul class="nav navbar-nav pull-right">
                <li><%= link_to "Home", root_path %></li>
                <%if signed_in?%>
                    <li id="fat-menu" class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <%if current_user.image%>
                            <%=image_tag(current_user.image, size: "20x20")%>
                        <% end %>
                        <%=current_user.name%><b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu">
                        <li>
                          <%= link_to "Sign out", sign_out_path, method: "delete" %>
                        </li>
                      </ul>
                    </li>
                <%else%>
                    <li><%= link_to "Sign in", login_path %></li>
                <%end%>
              </ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_meta_tags.html.erb
<%= csrf_meta_tags %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= render 'layouts/meta_tags' %>
  <%= stylesheet_link_tag "application", media: "all",
                          "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <% if content_for?(:script) %>
      <%= yield(:script) %>
  <% end %>
  <%= render 'layouts/shim' %>
</head>
<body id="body">
<%= render 'layouts/header' %>
<section id="spinner" class="spinner-2">
  <div class="spinner"></div>
</section>
<div id="page-body" class="container">
  <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8"><%= yield %></div>
    <div class="col-md-2"></div>
  </div>
  <%= render 'layouts/footer' %>
  <% if Rails.env.development? %>
      <%= debug(request.request_method()) %>
      <%= debug(request.server_software()) %>
      <%= debug(request.uuid()) %>
      <%= debug(params) %>
  <% end  %>
</div>
</body>
</html>